# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWNiMzgwMTkzMTAxYTVlOWE4ZTQyMzg2ZTAyYzkwZWRiOWExNzA0Y2ExMzBhZmIyYTc0YzNiYzFiNjVhYjYyMWM2NWMxMzViN2Y3ZTM2YTEwODMwNWVkYTgzYTVlOTVmZmFlMThhYTJmMjdiMjJkMWFjNzk2YTQ1MDg5Mzc4ZWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
